### ISSUE TITLE
bde_test_metadata fails in 

### ISSUE THREAD

**Issue by hillu** [libyal/libbde#14]
On a number of architectures, libbde failed to build due to crashes in the test suite, see https://buildd.debian.org/status/logs.php?pkg=libbde&ver=20170204-1.

I decided to take a closer look on i386:
```
$ LD_LIBRARY_PATH=../libbde/.libs/ gdb ./.libs/bde_test_metadata
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./.libs/bde_test_metadata...done.
(gdb) run
Starting program: /home/bengen/p/deb/plaso/libbde/tests/.libs/bde_test_metadata 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0xb7ebfea4 in libcdata_array_free (array=0x8000608c, 
    entry_free_function=0xb7eb2d6a <libbde_metadata_entry_free>, error=0x0)
    at libcdata_array.c:252
(gdb) p internal_array
$1 = (libcdata_internal_array_t *) 0x49
(gdb) bt
#0  0xb7ebfea4 in libcdata_array_free (array=0x8000608c, 
    entry_free_function=0xb7eb2d6a <libbde_metadata_entry_free>, error=0x0)
    at libcdata_array.c:252
#1  0xb7eae94e in libbde_metadata_initialize (metadata=0xbfffed0c, 
    error=0xbfffed08) at libbde_metadata.c:145
#2  0x80001061 in bde_test_metadata_initialize () at bde_test_metadata.c:182
#3  0x80002d31 in main (argc=1, argv=0xbfffede4) at bde_test_metadata.c:1110
(gdb) 
```

I was reminded of the bug I reported against libbfio (https://github.com/libyal/libbfio/issues/2) so I just went ahead and disabled the memory tests altogether when building the Debian package.

**Comment by joachimmetz** [comment]
I'll have a look when time permits, this maybe due to libbde test framework not being updated yet

**Comment by joachimmetz** [comment]
I've updated the test code in: https://github.com/libyal/libbde/commit/9419c28cea78ff63aa9cb988917a1c8e3ecb45ea

**Comment by joachimmetz** [comment]
@hillu this should be fixed now. New release pending.
